version: "3.3"
services:
  aluraflix-app:
    image: britto/aluraflix:v1.0
    container_name: aluraflix-app
    volumes:
      - sqlite:/usr/src/app/db
    ports:
      - 8000:8000

volumes:
  sqlite: