apiVersion: v1
kind: Pod
metadata:
  name: aluraflix-pod
spec:
  containers:
  - name: aluraflix-app
    image: britto/aluraflix:v1.0
    ports:
    - containerPort: 8000
      hostPort: 8000
    volumeMounts:
      - name: sqlite-volume
        mountPath: /usr/src/app/db
  volumes: 
  - name: sqlite-volume
    hostPath: 
      path: /tmp
      type: DirectoryOrCreate